source 'https://rubygems.org'

gem 'rspec', '~> 3.4'
gem 'rest-client', '~> 1.8.0'
gem 'rake', '~> 11.1.2'
gem 'page-object', '~> 2.0'
gem 'capybara', '~> 2.7', '>= 2.7.1'
gem 'test-unit', '~> 3.1', '>= 3.1.8'



group :test do
  gem "watir-rspec"
end