source 'https://rubygems.org'

gem 'rspec', '~> 3.4'
gem 'rest-client', '~> 1.8.0'
gem 'rake', '~> 11.1.2'
gem 'page-object', '~> 2.0'
gem 'capybara', '~> 2.7', '>= 2.7.1'
gem 'test-unit', '~> 3.1', '>= 3.1.8'
gem 'rest-open-uri', '~> 1.0'
gem 'json', '~> 1.7.1'
gem 'rest-client', '~> 1.8'
gem 'rubysl-base64', '~> 2.0'
gem 'xml-simple', '~> 1.1', '>= 1.1.5'
gem 'openssl', '~> 2.0', '>= 2.0.3'
gem 'nori', '~> 2.6'
gem 'smarter_csv', '~> 1.1'
gem 'activesupport', '~> 5.0'

group :test do
  gem "watir-rspec"
end